name: Loka-Orð

on:
  # Trigger workflow on any pull request
  pull_request:
  # Trigger workflow on pushes to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Initialize database
        run: |
          # smíða grunn
          python main.py build-db runtime
          # skrifa orð úr grunni í textaskrár
          python main.py write-files runtime
          # smíða orðaforleit
          python main.py build-sight
          # prófa orðaforleit
          python main.py search "orð"
          python main.py scan-sentence "Hér er haugur orða í hóflega langri setningu."
          # prenta út töluleg gögn á markdown sniði
          python main.py md-stats
          # ganga úr skugga um að orð séu óbreytt eftir smíði
          python main.py assert-clean-git
          # keyra webpack, nemur kennistrengur endurtekningar
          python main.py webpack
