name: Loka-Orð

on:
  # Trigger workflow on any pull request
  pull_request:
  # Trigger workflow on pushes to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Initialize and testrun database
        run: |
          # keyra prófanir fyrir orðagrunn
          # nota backup sqlite skrá til að stytta CI build tíma (í stað build-db)
          python main.py use-backup runtime
          # athuga hvort nokkuð samsett orð sé skilgreint samsett í hring
          python main.py check-samsett-circular-definitions runtime
          # skrifa orð úr grunni í textaskrár
          python main.py write-files runtime
          # smíða orðaforleit
          python main.py build-sight
          # prófa orðaforleit
          python main.py search "orð"
          python main.py scan-sentence "Hér er haugur orða í hóflega langri setningu."
          # prenta út töluleg gögn á markdown sniði
          python main.py md-stats
          # ganga úr skugga um að orð séu óbreytt eftir smíði
          python main.py assert-clean-git
          # keyra webpack, nemur m.a. hugsanlegar "kennistrengur" endurtekningar
          python main.py webpack
